name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  ci:
    name: Continous integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5' 
      - name: Build
        run: |
          make build
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
      - name: Lint
        run: |
          make lint
      - name: Test
        run: |
          make test